#!/bin/sh -l
set -euo pipefail

if [ -n "$*" ]; then
  exec "$@"
fi

if ! [ -f "${IMAGE_CRONTAB_FILE}" ]; then
  echo "${IMAGE_CRONTAB_FILE} doesn't exist or is not a file" >&2
  exit 1
fi

crontab "${IMAGE_CRONTAB_FILE}"

exec crond -f -L /dev/stdout
