#!/bin/sh -l
set -euo pipefail

if [ -n "$*" ]; then
  exec "$@"
fi

if ! [ -f "${IMAGE_CRONTAB_FILE}" ]; then
  echo "${IMAGE_CRONTAB_FILE} doesn't exist or is not a file" >&2
  exit 1
fi

crontab "${IMAGE_CRONTAB_FILE}"

if [ -n "${IMAGE_EXPORTER_PORT}" ]; then
  mkdir -p "${IMAGE_METRICS_DIR}"
  pushd "${IMAGE_METRICS_DIR}"
  python3 -m http.server "${IMAGE_EXPORTER_PORT}" &
  popd
fi

exec crond -f -L /dev/stdout
